In [ ]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = {
    'Age': ['Youth','Youth', 'Middle', 'Senior', 'Senior', 'Middle', 'Senior', 'Youth', 'Youth', 'Senior', 'Youth','Middle', 'Middle', 'Senior'],
    'Income': ['High', 'High', 'High', 'Medium', 'Low', 'Low', 'Low', 'Medium','LoW','Medium', 'Medium', 'Medium', 'High', 'Medium'],
    'Student': ['No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes','Yes','No', 'Yes', 'No'],
    'CreditRating': ['Fair', 'Excellent', 'Fair', 'Fair','Fair', 'Excellent', 'Excellent','Fair','Fair', 'Fair', 'Excellent', 'Excellent', 'Fair', 'Excellent'],
    'BuysComputer': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes','Yes', 'Yes', 'Yes', 'No']
}

In [ ]:
df = pd.DataFrame(data)
df

       Age  Income Student CreditRating BuysComputer
0    Youth    High      No         Fair           No
1    Youth    High      No    Excellent           No
2   Middle    High      No         Fair          Yes
3   Senior  Medium      No         Fair          Yes
4   Senior     Low     Yes         Fair          Yes
5   Middle     Low     Yes    Excellent           No
6   Senior     Low     Yes    Excellent          Yes
7    Youth  Medium      No         Fair           No
8    Youth     LoW     Yes         Fair          Yes
9   Senior  Medium     Yes         Fair          Yes
10   Youth  Medium     Yes    Excellent          Yes
11  Middle  Medium      No    Excellent          Yes
12  Middle    High     Yes         Fair          Yes
13  Senior  Medium      No    Excellent           No

In [ ]:
le = {}  # create empty dictionary
df_enc = df.copy()  # here we just cop our original data
for col in df.columns:  # it convert into the text using loop through of the c
    le[col] = LabelEncoder()  # now create new label for current data
    df_enc[col] = le[col].fit_transform(df[col])  # its learn unique value and

In [ ]:
df_enc

    Age  Income  Student  CreditRating  BuysComputer
0     2       0        0             1             0
1     2       0        0             0             0
2     0       0        0             1             1
3     1       3        0             1             1
4     1       2        1             1             1
5     0       2        1             0             0
6     1       2        1             0             1
7     2       3        0             1             0
8     2       1        1             1             1
9     1       3        1             1             1
10    2       3        1             0             1
11    0       3        0             0             1
12    0       0        1             1             1
13    1       3        0             0             0

In [ ]:
x = df_enc[['Age', 'Income', 'Student', 'CreditRating']]
y = df_enc[['BuysComputer']]

In [ ]:
x

    Age  Income  Student  CreditRating
0     2       0        0             1
1     2       0        0             0
2     0       0        0             1
3     1       3        0             1
4     1       2        1             1
5     0       2        1             0
6     1       2        1             0
7     2       3        0             1
8     2       1        1             1
9     1       3        1             1
10    2       3        1             0
11    0       3        0             0
12    0       0        1             1
13    1       3        0             0

In [ ]:
model = CategoricalNB() #apply model
model.fit(x,y) # here fit your values

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

CategoricalNB()

In [ ]:
test = [['Youth', 'Medium', 'Yes', 'Fair']] # testing data

In [ ]:
test

[['youth', 'Medium', 'Yes', 'Fair']]

In [ ]:
print("\n------------------- Prediction -------------------\n")
for t in test:
    row = [[
        le['Age'].transform([t[0]])[0],
        le['Income'].transform([t[1]])[0],
        le['Student'].transform([t[2]])[0],
        le['CreditRating'].transform([t[3]])[0]
    ]]

    pred = le['BuysComputer'].inverse_transform(model.predict(row))[0]
    prob = model.predict_proba(row)[0]

    print(f"Input : Age={t[0]}, Income={t[1]}, Student={t[2]}, CreditRating={t[3]}")
    print(f"Result: Buys Computer -> {pred}")
    print(f"P(No)  = {prob[0]:.4f}")
    print(f"P(Yes) = {prob[1]:.4f}")

------------------- Prediction -------------------

Input : Age=Youth, Income=Medium, Student=Yes, CreditRating=Fair
Result: Buys Computer -> Yes
P(No)  = 0.2255
P(Yes) = 0.7745

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(